version: "3"

services:
  kraftwerk:
    image: lucaheitmann/kraftwerk-activity-tracker
    environment:
      - INTERVAL_SECONDS=10
      - OUTPUT_FILE=/data/output.csv
    volumes:
      - ./data:/data:z
